
name: Web Update

on:
  release:
    types: [published]
  # Testing
  pull_request:
    branches: [ "main" ]

jobs:
  trigger-pages-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.repos.createDispatchEvent({
              owner: "dn-vm",
              repo: "dn-vm.github.io",
              event_type: "new_release"
            })
