
name: Web Update

on:
  release:
    types: [published]

jobs:
  trigger-pages-workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Sleep for 5 minutes
        run: sleep 5m
        shell: bash
      - name: Trigger Workflow
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.REPO_DISPATCH_TOKEN }}
          script: |
            github.rest.repos.createDispatchEvent({
              owner: "dn-vm",
              repo: "dn-vm.github.io",
              event_type: "new_release"
            })
